LIBNAME FINAL "C:\Users\12035\Downloads\2021-nyts-dataset-format-library-codebook-sas (2)\2021-nyts-dataset-format-library-codebook-sas";
RUN;

DATA YOUTH;
SET FINAL.NYTS2021;
WHERE QN33C=1;
RUN;

PROC FORMAT;
VALUE AGEGROUP  9-13 = 'YOUNGER AGE'
                14-18='MIDDLE AGE'
                 19-HIGH= 'OLDER AGE'
                 OTHER = 'MISSING';
VALUE GENDER  1='MALE'
               2='FEMALE';
VALUE  GRADE    1-3 ='MIDDLE SCHOOL'
                4-8 ='HIGH SCHOOL'
               OTHER = 'MISSING';
RUN;

DATA VAPE_RACE;
SET YOUTH;
IF QN5A=1 THEN RACE = 'NATIVE';
ELSE IF QN5B =1 THEN RACE = 'ASIAN';
ELSE IF QN5B =1 THEN RACE ='BLACK';
ELSE IF QN5D = 1 THEN RACE = 'HAWAIIAN';
ELSE IF QN5E = 1 THEN RACE = 'WHITIE';
RUN;
PROC PRINT DATA=VAPE_RACE;
RUN;


TITLE “NEW VARIABLE CALLED THIRTY DAYS VAPING”;
DATA VAPETHIRTHY;
SET YOUTH;
IF QN34A = 1 THEN VAPING='MARIJUANA';
ELSE IF QN34B = 1 THEN VAPING ='CBD';
ELSE IF QN34C = 1 THEN VAPING ='SYNMARIJUANA';
ELSE IF QN34D =1 THEN VAPING ='OTHER SUBS';
RUN;


TITLE "STATISTICS ACCORDING TO AGE";
PROC FREQ DATA=YOUTH  (WHERE =(QN1 IS NOT MISSING)) ;
TABLE QN1 /NOCUM;
LABEL QN1=' AGE';
FORMAT QN1 AGEGROUP.;
RUN;

 TITLE "STATISTICS ACCORDING TO GENDER";
 PROC FREQ DATA= YOUTH (WHERE =(QN2 IS NOT MISSING));
 TABLE QN2 / NOCUM;
 FORMAT  QN2 GENDER.;
 RUN;

TITLE "VAPING ACCORDING TO AGE AND GENDER";
PROC FREQ DATA = YOUTH (WHERE=(QN1 AND QN2 IS NOT MISSING));
LABEL QN1= 'AGEGROUP'
      QN2= 'GENDER';
TABLE QN1 *QN2/ NOCOL NOROW;
FORMAT QN1 AGEGROUP.
       QN2 GENDER.;
RUN;

TITLE "VAPING ACCORDING TO GRADE LEVEL";
PROC FREQ DATA=YOUTH (WHERE =(QN3 IS NOT MISSING));
TABLE QN3/NOCUM;
FORMAT QN3 GRADE.;
RUN;

TITLE "SGPLOT ACCORDING TO GRADE LEVEL";
PROC SGPLOT DATA=VAPE_RACE (WHERE =(RACE IS NOT MISSING));
VBAR RACE;
RUN;
