LIBNAME FINAL "C:\Users\12035\Downloads\2021-nyts-dataset-format-library-codebook-sas (2)\2021-nyts-dataset-format-library-codebook-sas";
RUN;

*CREATE A NEW DATA SET CALLED YOUTH FROM THE DOWNLOADED DATASET NYTS2021;
DATA YOUTH;
SET FINAL.NYTS2021;
WHERE QN33C=1;
RUN;


* USER DEFINED FORMATS FOR THREE VARIABLES FOR CATEGORIZATION; 
* VALUE AGE GROUP: 9-12 YEARS= YOUNGER AGE,13-16YEARS =MIDDLE AGE,17 YEARS AND ABOVE =OLDER AGE;
*VALUE GRADE:6TH-8TH GRADE=MIDDLE SCHOOL,9-12TH GRAGE=HIGH SCHOOL;
PROC FORMAT;
VALUE AGEGROUP  1-4 = 'YOUNGER AGE'
                5-8='MIDDLE AGE'
                 9-11='OLDER AGE'
                 OTHER = 'MISSING';
VALUE GENDER  1='MALE'
               2='FEMALE';
VALUE  GRADE    1-3 ='MIDDLE SCHOOL'
                4-7 ='HIGH SCHOOL'
				8='UNGRADED OR OTHER'
               OTHER = 'MISSING';
RUN;


*CREATING A NEW VARIABLE IN THE YOUTH DATASET BASED ON RESPONSE TO QN5B,QN5C,QN5D,QN5E;
DATA VAPE_RACE;
SET YOUTH;
IF QN5A=1 THEN RACE = 'NATIVE ';
ELSE IF QN5B =1 THEN RACE = 'ASIAN';
ELSE IF QN5C =1 THEN RACE ='BLACK';
ELSE IF QN5D = 1 THEN RACE = 'HAWAIIAN';
ELSE IF QN5E = 1 THEN RACE = 'WHITIE';
RUN;


*IF RESPONDED YES TO VAPING,  WHAT SUBSTANCE DID THEY VAPE IN THIRTY DAYS;
*MARIJUANA ,CBD,SYNTHETIC MARIJUANA(SYN MAR) AND OTHER SUBSTANCES(OTHER SUBS);
TITLE “NEW VARIABLE CALLED THIRTY DAYS VAPING”;
DATA VAPETHIRTHY;
SET YOUTH;
IF QN34A = 1 THEN VAPING='MARIJUANA';
ELSE IF QN34B = 1 THEN VAPING ='CBD';
ELSE IF QN34C = 1 THEN VAPING ='SYN MAR';
ELSE IF QN34D =1 THEN VAPING ='OTHER SUBS';
RUN;
PROC PRINT DATA =VAPETHIRTHY;
RUN;

*AMONG THOSE WHO RESPONDED TO WHAT TYPE OF SUBSTANCE THEY USED FOR VAPING THIS PROCEDURE INFORMS US WHICH  
SUBSTANCE WAS MORE FREQUENTLY USED FOR VAPING;
PROC FREQ DATA=VAPETHIRTHY (WHERE=(VAPING  IS NOT MISSING));
TITLE "TO ANSWER WHICH SUBSTANCE WAS MOSTLY USED AMONG YOUTH";
TABLES VAPING/NOCUM ;
RUN;


TITLE "VAPING  IN THREE AGE GROUPS";
PROC FREQ DATA=YOUTH  (WHERE =(QN1 IS NOT MISSING)) ;
TABLE QN1 /NOCUM;
LABEL QN1=' AGE';
FORMAT QN1 AGEGROUP.;
RUN;

 TITLE "VAPING IN MALE AND FEMALE GENDER";
 PROC FREQ DATA= YOUTH (WHERE =(QN2 IS NOT MISSING));
 TABLE QN2 / NOCUM;
 FORMAT  QN2 GENDER.;
 RUN;

TITLE "VAPING ACCORDING TO AGE AND GENDER";
PROC FREQ DATA = YOUTH (WHERE=(QN1 AND QN2 IS NOT MISSING));
LABEL QN1= 'AGEGROUP'
      QN2= 'GENDER';
TABLE QN1 *QN2/ NOCOL NOROW;
FORMAT QN1 AGEGROUP.
       QN2 GENDER.;
RUN;

TITLE "VAPING ACCORDING TO GRADE";
PROC FREQ DATA=YOUTH (WHERE =(QN3 IS NOT MISSING));
TABLE QN3/NOCUM;
FORMAT QN3 GRADE.;
RUN;

TITLE "SGPLOT  FOR VAPING IN  DIFFERENT RACES";
PROC SGPLOT DATA=VAPE_RACE (WHERE =(RACE IS NOT MISSING));
VBAR RACE;
RUN;



